# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Allan\Desktop\Pastas\SnesGameManager-windows\config\ui\emuConfig_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_emuDialog(object):
    def setupUi(self, emuDialog):
        emuDialog.setObjectName("emuDialog")
        emuDialog.resize(406, 220)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(emuDialog.sizePolicy().hasHeightForWidth())
        emuDialog.setSizePolicy(sizePolicy)
        emuDialog.setMinimumSize(QtCore.QSize(406, 220))
        emuDialog.setMaximumSize(QtCore.QSize(406, 220))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        emuDialog.setFont(font)
        emuDialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        emuDialog.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(emuDialog)
        self.verticalLayout.setContentsMargins(4, 0, 4, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(emuDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(30, -1, 30, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setMidLineWidth(0)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.emuBox = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emuBox.sizePolicy().hasHeightForWidth())
        self.emuBox.setSizePolicy(sizePolicy)
        self.emuBox.setMinimumSize(QtCore.QSize(10, 0))
        self.emuBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.emuBox.setObjectName("emuBox")
        self.horizontalLayout_2.addWidget(self.emuBox)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(emuDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(10, 50))
        self.frame.setBaseSize(QtCore.QSize(10, 10))
        self.frame.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(80, -1, 80, -1)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.btSearch = QtWidgets.QToolButton(self.frame)
        self.btSearch.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btSearch.setAutoRaise(False)
        self.btSearch.setArrowType(QtCore.Qt.NoArrow)
        self.btSearch.setObjectName("btSearch")
        self.gridLayout.addWidget(self.btSearch, 1, 2, 1, 1)
        self.txtBox = QtWidgets.QLineEdit(self.frame)
        self.txtBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtBox.sizePolicy().hasHeightForWidth())
        self.txtBox.setSizePolicy(sizePolicy)
        self.txtBox.setMinimumSize(QtCore.QSize(206, 0))
        self.txtBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtBox.setBaseSize(QtCore.QSize(0, 0))
        self.txtBox.setObjectName("txtBox")
        self.gridLayout.addWidget(self.txtBox, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(emuDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btCancel = QtWidgets.QPushButton(self.frame_3)
        self.btCancel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btCancel.setCheckable(False)
        self.btCancel.setChecked(False)
        self.btCancel.setAutoDefault(True)
        self.btCancel.setDefault(False)
        self.btCancel.setFlat(False)
        self.btCancel.setObjectName("btCancel")
        self.horizontalLayout.addWidget(self.btCancel)
        self.btApply = QtWidgets.QPushButton(self.frame_3)
        self.btApply.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btApply.setObjectName("btApply")
        self.horizontalLayout.addWidget(self.btApply)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(emuDialog)
        QtCore.QMetaObject.connectSlotsByName(emuDialog)

    def retranslateUi(self, emuDialog):
        _translate = QtCore.QCoreApplication.translate
        emuDialog.setWindowTitle(_translate("emuDialog", "Emulator configuration"))
        self.label.setText(_translate("emuDialog", "Default emulator:"))
        self.label_2.setText(_translate("emuDialog", "Emulator executable path"))
        self.btSearch.setText(_translate("emuDialog", "..."))
        self.btCancel.setText(_translate("emuDialog", "Cancel"))
        self.btApply.setText(_translate("emuDialog", "Apply"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    emuDialog = QtWidgets.QDialog()
    ui = Ui_emuDialog()
    ui.setupUi(emuDialog)
    emuDialog.show()
    sys.exit(app.exec_())
